title: Hao Yan
position: Biostatistics Ph.D. Candidate 
affiliation: UT MD Anderson Cancer Center
email: hyan5@mdanderson.edu
keywords:
google_scholar:
github_link: https://github.com/JoJoDeee
linkedin: https://www.linkedin.com/in/yan-hao-7a0382106/
cv_link: 
avatar: ./assets/img/IMG_1078.jpg
google_analytics: 
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: 
canonical: https://strata-academic.yyliu.net/
remote_theme: yaoyao-liu/strata-academic
